### ISSUE TITLE
建议给代码对应的具体问题贴一个链接

### ISSUE THREAD

**Issue by ResolveWang** [FlushHip/mygit#1]
感谢作者的项目，提一个小小的建议，给代码对应的具体问题贴一个问题描述链接或者简要叙述一下问题，给个解题思路的链接，这样的话受众会更广

**Comment by FlushHip** [comment]
好的，谢谢大佬的建议，之前都是在CSDN上写博客，对GitHub了解不多，希望能和大佬持续交流，我的CSDN博客：https://blog.csdn.net/FlushHip
